services:
  postgres:
    container_name: expensegate-db
    image: postgres:14.19-trixie
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-67a55ba2ce4c466c57fcb909f180fe05}
      POSTGRES_DB: ${POSTGRES_DB:-expensegate-db}
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib"

volumes:
  pg_data: {}