spring.application.name=expensegate

spring.datasource.url=jdbc:postgresql://localhost:5432/expensegate-db
spring.datasource.username=admin
spring.datasource.password=67a55ba2ce4c466c57fcb909f180fe05

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true